# Generated by Django 3.0.3 on 2020-02-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200218_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='origin_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
