# Generated by Django 3.0.3 on 2020-02-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200218_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='sale_price',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
