# Generated by Django 3.0.3 on 2020-02-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200218_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
