# Generated by Django 3.0.2 on 2020-02-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200216_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='homepage',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
